-- Eliminar tablas si existen para empezar limpio
DROP TABLE IF EXISTS modificaciones CASCADE;
DROP TABLE IF EXISTS reservaciones CASCADE;
DROP TABLE IF EXISTS municipios CASCADE;
DROP TABLE IF EXISTS departamentos CASCADE;
DROP TABLE IF EXISTS asientos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE "usuarios" (
  "usuario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "nombre_completo" varchar(255) NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "asientos" (
  "asiento_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_asiento" varchar(3) UNIQUE NOT NULL,
  "clase_asiento" varchar(10) NOT NULL
);

CREATE TABLE "reservaciones" (
  "reservacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "asiento_id" int NOT NULL,
  "nombre_pasajero" varchar(255) NOT NULL,
  "cui_pasajero" varchar(13) NOT NULL,
  "tiene_equipaje" boolean NOT NULL DEFAULT false,
  "fecha_reservacion" timestamp DEFAULT (now()),
  "estado" varchar(10) NOT NULL DEFAULT 'ACTIVA',
  "metodo_seleccion" varchar(10) NOT NULL,
  "precio_base" decimal(10,2) NOT NULL,
  "precio_total" decimal(10,2) NOT NULL
);

CREATE TABLE "modificaciones" (
  "modificacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservacion_id" int NOT NULL,
  "fecha_modificacion" timestamp DEFAULT (now()),
  "recargo_aplicado" decimal(10,2) NOT NULL
);

CREATE TABLE "departamentos" (
  "departamento_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(2) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL
);

CREATE TABLE "municipios" (
  "municipio_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departamento_id" int NOT NULL,
  "codigo" varchar(3) UNIQUE NOT NULL,  -- Cambiado a varchar(3)
  "nombre" varchar(100) NOT NULL
);

-- Ahora agregar las llaves foráneas (después de crear todas las tablas)
ALTER TABLE "reservaciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("usuario_id");
ALTER TABLE "reservaciones" ADD FOREIGN KEY ("asiento_id") REFERENCES "asientos" ("asiento_id");
ALTER TABLE "modificaciones" ADD FOREIGN KEY ("reservacion_id") REFERENCES "reservaciones" ("reservacion_id");
ALTER TABLE "municipios" ADD FOREIGN KEY ("departamento_id") REFERENCES "departamentos" ("departamento_id");

-- Los COMMENT deben ir después de crear las tablas
COMMENT ON COLUMN "asientos"."clase_asiento" IS '''Negocios'' o ''Economica''';
COMMENT ON COLUMN "reservaciones"."estado" IS '''ACTIVA'' o ''CANCELADA''';
COMMENT ON COLUMN "reservaciones"."metodo_seleccion" IS '''Manual'' o ''Aleatorio''';

-- Poblar la tabla de asientos
INSERT INTO asientos (numero_asiento, clase_asiento) VALUES
('I1', 'Negocios'), ('I2', 'Negocios'),
('G1', 'Negocios'), ('G2', 'Negocios'),
('F1', 'Negocios'), ('F2', 'Negocios'),
('D1', 'Negocios'), ('D2', 'Negocios'),
('C1', 'Negocios'), ('C2', 'Negocios'),
('A1', 'Negocios'), ('A2', 'Negocios'),
('I3', 'Economica'), ('I4', 'Economica'), ('I5', 'Economica'), ('I6', 'Economica'), ('I7', 'Economica'),
('H3', 'Economica'), ('H4', 'Economica'), ('H5', 'Economica'), ('H6', 'Economica'), ('H7', 'Economica'),
('G3', 'Economica'), ('G4', 'Economica'), ('G5', 'Economica'), ('G6', 'Economica'), ('G7', 'Economica'),
('F3', 'Economica'), ('F4', 'Economica'), ('F5', 'Economica'), ('F6', 'Economica'), ('F7', 'Economica'),
('E3', 'Economica'), ('E4', 'Economica'), ('E5', 'Economica'), ('E6', 'Economica'), ('E7', 'Economica'),
('D3', 'Economica'), ('D4', 'Economica'), ('D5', 'Economica'), ('D6', 'Economica'), ('D7', 'Economica'),
('C3', 'Economica'), ('C4', 'Economica'), ('C5', 'Economica'), ('C6', 'Economica'), ('C7', 'Economica'),
('B3', 'Economica'), ('B4', 'Economica'), ('B5', 'Economica'), ('B6', 'Economica'), ('B7', 'Economica'),
('A3', 'Economica'), ('A4', 'Economica'), ('A5', 'Economica'), ('A6', 'Economica'), ('A7', 'Economica');

-- Limpiar e insertar departamentos
DELETE FROM departamentos;  -- Limpiar primero si existe data
INSERT INTO "departamentos" ("codigo", "nombre") VALUES
('01', 'GUATEMALA'),
('02', 'EL PROGRESO'),
('03', 'SACATEPEQUEZ'),
('04', 'CHIMALTENANGO'),
('05', 'ESCUINTLA'),
('06', 'SANTA ROSA'),
('07', 'SOLOLA'),
('08', 'TOTONICAPAN'),
('09', 'QUETZALTENANGO'),
('10', 'SUCHITEPEQUEZ'),
('11', 'RETALHULEU'),
('12', 'SAN MARCOS'),
('13', 'HUEHUETENANGO'),
('14', 'EL QUICHE'),
('15', 'BAJA VERAPAZ'),
('16', 'ALTA VERAPAZ'),
('17', 'PETEN'),
('18', 'IZABAL'),
('19', 'ZACAPA'),
('20', 'CHIQUIMULA'),
('21', 'JALAPA'),
('22', 'JUTIAPA');

-- Limpiar e insertar municipios
DELETE FROM municipios;  -- Limpiar primero
INSERT INTO "municipios" ("departamento_id", "codigo", "nombre") VALUES
-- GUATEMALA
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '01', 'GUATEMALA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '02', 'SANTA CATARINA PINULA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '03', 'SAN JOSE PINULA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '04', 'SAN JOSE DEL GOLFO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '05', 'PALENCIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '06', 'CHINAUTLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '07', 'SAN PEDRO AYAMPUC'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '08', 'MIXCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '09', 'SAN PEDRO SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '10', 'SAN JUAN SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '11', 'SAN RAYMUNDO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '12', 'CHUARRANCHO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '13', 'FRAIJANES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '14', 'AMATITLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '15', 'VILLA NUEVA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '16', 'VILLA CANALES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '17', 'SAN MIGUEL PETAPA');

-- Continuar con el resto de municipios (he abreviado para el ejemplo)
