-- Eliminar tablas si existen para empezar limpio
DROP TABLE IF EXISTS modificaciones CASCADE;
DROP TABLE IF EXISTS reservaciones CASCADE;
DROP TABLE IF EXISTS municipios CASCADE;
DROP TABLE IF EXISTS departamentos CASCADE;
DROP TABLE IF EXISTS asientos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE "usuarios" (
  "usuario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "nombre_completo" varchar(255) NOT NULL,
  "fecha_creacion" timestamp DEFAULT (now())
);

CREATE TABLE "asientos" (
  "asiento_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_asiento" varchar(3) UNIQUE NOT NULL,
  "clase_asiento" varchar(10) NOT NULL
);

CREATE TABLE "reservaciones" (
  "reservacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "asiento_id" int NOT NULL,
  "nombre_pasajero" varchar(255) NOT NULL,
  "cui_pasajero" varchar(13) NOT NULL,
  "tiene_equipaje" boolean NOT NULL DEFAULT false,
  "fecha_reservacion" timestamp DEFAULT (now()),
  "estado" varchar(10) NOT NULL DEFAULT 'ACTIVA',
  "metodo_seleccion" varchar(10) NOT NULL,
  "precio_base" decimal(10,2) NOT NULL,
  "precio_total" decimal(10,2) NOT NULL
);

CREATE TABLE "modificaciones" (
  "modificacion_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservacion_id" int NOT NULL,
  "fecha_modificacion" timestamp DEFAULT (now()),
  "recargo_aplicado" decimal(10,2) NOT NULL
);

CREATE TABLE "departamentos" (
  "departamento_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(2) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL
);

CREATE TABLE "municipios" (
  "municipio_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departamento_id" int NOT NULL,
  "codigo" varchar(3) NOT NULL,  -- Cambiado a varchar(3)
  "nombre" varchar(100) NOT NULL
);

-- Ahora agregar las llaves foráneas (después de crear todas las tablas)
ALTER TABLE "reservaciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("usuario_id");
ALTER TABLE "reservaciones" ADD FOREIGN KEY ("asiento_id") REFERENCES "asientos" ("asiento_id");
ALTER TABLE "modificaciones" ADD FOREIGN KEY ("reservacion_id") REFERENCES "reservaciones" ("reservacion_id");
ALTER TABLE "municipios" ADD FOREIGN KEY ("departamento_id") REFERENCES "departamentos" ("departamento_id");

-- Los COMMENT deben ir después de crear las tablas
COMMENT ON COLUMN "asientos"."clase_asiento" IS '''Negocios'' o ''Economica''';
COMMENT ON COLUMN "reservaciones"."estado" IS '''ACTIVA'' o ''CANCELADA''';
COMMENT ON COLUMN "reservaciones"."metodo_seleccion" IS '''Manual'' o ''Aleatorio''';

-- Poblar la tabla de asientos
INSERT INTO asientos (numero_asiento, clase_asiento) VALUES
('I1', 'Negocios'), ('I2', 'Negocios'),
('G1', 'Negocios'), ('G2', 'Negocios'),
('F1', 'Negocios'), ('F2', 'Negocios'),
('D1', 'Negocios'), ('D2', 'Negocios'),
('C1', 'Negocios'), ('C2', 'Negocios'),
('A1', 'Negocios'), ('A2', 'Negocios'),
('I3', 'Economica'), ('I4', 'Economica'), ('I5', 'Economica'), ('I6', 'Economica'), ('I7', 'Economica'),
('H3', 'Economica'), ('H4', 'Economica'), ('H5', 'Economica'), ('H6', 'Economica'), ('H7', 'Economica'),
('G3', 'Economica'), ('G4', 'Economica'), ('G5', 'Economica'), ('G6', 'Economica'), ('G7', 'Economica'),
('F3', 'Economica'), ('F4', 'Economica'), ('F5', 'Economica'), ('F6', 'Economica'), ('F7', 'Economica'),
('E3', 'Economica'), ('E4', 'Economica'), ('E5', 'Economica'), ('E6', 'Economica'), ('E7', 'Economica'),
('D3', 'Economica'), ('D4', 'Economica'), ('D5', 'Economica'), ('D6', 'Economica'), ('D7', 'Economica'),
('C3', 'Economica'), ('C4', 'Economica'), ('C5', 'Economica'), ('C6', 'Economica'), ('C7', 'Economica'),
('B3', 'Economica'), ('B4', 'Economica'), ('B5', 'Economica'), ('B6', 'Economica'), ('B7', 'Economica'),
('A3', 'Economica'), ('A4', 'Economica'), ('A5', 'Economica'), ('A6', 'Economica'), ('A7', 'Economica');

-- Limpiar e insertar departamentos
DELETE FROM departamentos;  -- Limpiar primero si existe data
INSERT INTO "departamentos" ("codigo", "nombre") VALUES
('01', 'GUATEMALA'),
('02', 'EL PROGRESO'),
('03', 'SACATEPEQUEZ'),
('04', 'CHIMALTENANGO'),
('05', 'ESCUINTLA'),
('06', 'SANTA ROSA'),
('07', 'SOLOLA'),
('08', 'TOTONICAPAN'),
('09', 'QUETZALTENANGO'),
('10', 'SUCHITEPEQUEZ'),
('11', 'RETALHULEU'),
('12', 'SAN MARCOS'),
('13', 'HUEHUETENANGO'),
('14', 'EL QUICHE'),
('15', 'BAJA VERAPAZ'),
('16', 'ALTA VERAPAZ'),
('17', 'PETEN'),
('18', 'IZABAL'),
('19', 'ZACAPA'),
('20', 'CHIQUIMULA'),
('21', 'JALAPA'),
('22', 'JUTIAPA');

-- Limpiar e insertar municipios
DELETE FROM municipios;  -- Limpiar primero
INSERT INTO "municipios" ("departamento_id", "codigo", "nombre") VALUES
-- GUATEMALA
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '01', 'GUATEMALA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '02', 'SANTA CATARINA PINULA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '03', 'SAN JOSE PINULA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '04', 'SAN JOSE DEL GOLFO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '05', 'PALENCIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '06', 'CHINAUTLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '07', 'SAN PEDRO AYAMPUC'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '08', 'MIXCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '09', 'SAN PEDRO SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '14', 'AMATITLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '15', 'VILLA NUEVA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '16', 'VILLA CANALES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '01'), '17', 'SAN MIGUEL PETAPA');


INSERT INTO "municipios" ("departamento_id", "codigo", "nombre") VALUES
-- EL PROGRESO
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '01', 'GUASTATOYA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '02', 'MORAZAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '03', 'SAN AGUSTIN ACASAGUASTLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '04', 'SAN CRISTOBAL ACASAGUASTLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '05', 'EL JICARO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '06', 'SANSARE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '07', 'SANARATE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '02'), '08', 'SAN ANTONIO LA PAZ'),

-- SACATEPEQUEZ
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '01', 'ANTIGUA GUATEMALA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '02', 'JOCOTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '03', 'PASTORES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '04', 'SUMPANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '05', 'SANTO DOMINGO XENACOJ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '06', 'SANTIAGO SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '07', 'SAN BARTOLOME MILPAS ALTAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '08', 'SAN LUCAS SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '09', 'SANTA LUCIA MILPAS ALTAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '10', 'MAGDALENA MILPAS ALTAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '11', 'SANTA MARIA DE JESUS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '12', 'CIUDAD VIEJA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '13', 'SAN MIGUEL DUENAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '14', 'ALOTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '15', 'SAN ANTONIO AGUAS CALIENTES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '03'), '16', 'SANTA CATARINA BARAHONA'),

-- CHIMALTENANGO
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '01', 'CHIMALTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '02', 'SAN JOSE POAQUIL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '03', 'SAN MARTIN JILOTEPEQUE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '04', 'SAN JUAN COMALAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '05', 'SANTA APOLONIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '06', 'TECPAN GUATEMALA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '07', 'PATZUN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '08', 'POCHUTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '09', 'PATZICIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '10', 'SANTA CRUZ BALANYA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '11', 'ACATENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '12', 'SAN PEDRO YEPOCAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '13', 'SAN ANDRES ITZAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '14', 'PARRAMOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '15', 'ZARAGOZA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '04'), '16', 'EL TEJAR'),

-- ESCUINTLA
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '01', 'ESCUINTLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '02', 'SANTA LUCIA COTZUMALGUAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '03', 'LA DEMOCRACIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '04', 'SIQUINALA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '05', 'MASAGUA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '06', 'TIQUISATE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '07', 'LA GOMERA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '08', 'GUANAGAZAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '09', 'SAN JOSE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '10', 'IZTAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '11', 'PALIN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '12', 'SAN VICENTE PACAYA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '13', 'NUEVA CONCEPCION'),
((SELECT departamento_id FROM departamentos WHERE codigo = '05'), '14', 'SIPACATE'),

-- SANTA ROSA
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '01', 'CUILAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '02', 'BARBERENA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '03', 'SANTA ROSA DE LIMA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '04', 'CASILLAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '05', 'SAN RAFAEL LAS FLORES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '06', 'ORATORIO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '07', 'SAN JUAN TECUACO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '08', 'CHIQUIMULILLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '09', 'TAXISCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '10', 'SANTA MARIA IXHUATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '11', 'GUAZACAPAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '12', 'SANTA CRUZ NARANJO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '13', 'PUEBLO NUEVO VINAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '06'), '14', 'NUEVA SANTA ROSA'),

-- SOLOLA
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '01', 'SOLOLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '02', 'CONCEPCION'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '03', 'NAHUALA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '04', 'PANAJACHEL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '05', 'SAN ANDRES SEMETABAJ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '06', 'SAN ANTONIO PALOPO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '07', 'SAN JOSE CHACAYA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '08', 'SAN JUAN LA LAGUNA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '09', 'SAN LUCAS TOLIMAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '10', 'SAN MARCOS LA LAGUNA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '11', 'SAN PABLO LA LAGUNA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '12', 'SAN PEDRO LA LAGUNA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '13', 'SANTA CATARINA IXTAHUACAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '14', 'SANTA CATARINA PALOPO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '15', 'SANTA CLARA LA LAGUNA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '16', 'SANTA CRUZ LA LAGUNA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '17', 'SANTA LUCIA UTATLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '18', 'SANTA MARIA VISITACION'),
((SELECT departamento_id FROM departamentos WHERE codigo = '07'), '19', 'SANTIAGO ATITLAN'),

-- TOTONICAPAN
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '01', 'TOTONICAPAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '02', 'MOMOSTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '03', 'SAN ANDRES XECUL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '04', 'SAN BARTOLO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '05', 'SAN CRISTOBAL TOTONICAPAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '06', 'SAN FRANCISCO EL ALTO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '07', 'SANTA LUCIA LA REFORMA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '08'), '08', 'SANTA MARIA CHIQUIMULA'),

-- QUETZALTENANGO
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '01', 'QUETZALTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '02', 'ALMOLONGA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '03', 'CABRICAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '04', 'CAJOLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '05', 'CANTEL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '06', 'COATEPEQUE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '07', 'COLOMBA COSTA CUCA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '08', 'CONCEPCION CHIQUIRICHAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '09', 'EL PALMAR'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '10', 'FLORES COSTA CUCA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '11', 'GENOVA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '12', 'HUITAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '13', 'LA ESPERANZA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '14', 'OLINTEPEQUE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '15', 'PALESTINA DE LOS ALTOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '16', 'SALCAJA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '17', 'SAN CARLOS SIJA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '18', 'SAN FRANCISCO LA UNION'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '19', 'SAN JUAN OSTUNCALCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '20', 'SAN MARTIN SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '21', 'SAN MATEO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '22', 'SAN MIGUEL SIGUILA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '23', 'SIBILIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '09'), '24', 'ZUNIL'),

-- SUCHITEPEQUEZ
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '01', 'MAZATENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '02', 'CHICACAO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '03', 'CUYOTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '04', 'PATULUL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '05', 'PUEBLO NUEVO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '06', 'RIO BRAVO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '07', 'SAMAYAC'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '08', 'SAN ANTONIO SUCHITEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '09', 'SAN BERNARDINO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '10', 'SAN FRANCISCO ZAPOTITLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '11', 'SAN GABRIEL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '12', 'SAN JOSE EL IDOLO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '13', 'SAN JOSE LA MAQUINA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '14', 'SAN JUAN BAUTISTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '15', 'SAN LORENZO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '16', 'SAN MIGUEL PANAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '17', 'SAN PABLO JOCOPILAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '18', 'SANTA BARBARA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '19', 'SANTO DOMINGO SUCHITEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '20', 'SANTO TOMAS LA UNION'),
((SELECT departamento_id FROM departamentos WHERE codigo = '10'), '21', 'ZUNILITO'),

-- RETALHULEU
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '01', 'RETALHULEU'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '02', 'CHAMPERICO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '03', 'EL ASINTAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '04', 'NUEVO SAN CARLOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '05', 'SAN ANDRES VILLA SECA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '06', 'SAN FELIPE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '07', 'SAN MARTIN ZAPOTITLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '08', 'SAN SEBASTIAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '11'), '09', 'SANTA CRUZ MULUA'),

-- SAN MARCOS
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '01', 'SAN MARCOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '02', 'AYUTLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '03', 'CATARINA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '04', 'COMITANCILLO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '05', 'CONCEPCION TUTUAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '06', 'EL QUETZAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '07', 'EL TUMBADOR'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '08', 'ESQUIPULAS PALO GORDO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '09', 'IXCHIGUAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '10', 'LA BLANCA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '11', 'LA REFORMA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '12', 'MALACATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '13', 'NUEVO PROGRESO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '14', 'OCOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '15', 'PAJAPITA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '16', 'RIO BLANCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '17', 'SAN ANTONIO SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '18', 'SAN CRISTOBAL CUCHO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '19', 'SAN JOSE EL RODEO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '20', 'SAN JOSE OJETENAM'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '21', 'SAN LORENZO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '22', 'SAN MIGUEL IXTAHUACAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '23', 'SAN PABLO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '24', 'SAN PEDRO SACATEPEQUEZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '25', 'SAN RAFAEL PIE DE LA CUESTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '26', 'SIBINAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '27', 'SIPACAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '28', 'TACANA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '29', 'TAJUMULCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '12'), '30', 'TEJUTLA'),

-- HUEHUETENANGO
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '01', 'HUEHUETENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '02', 'AGUACATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '03', 'CHIANTLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '04', 'COLOTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '05', 'CONCEPCION HUISTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '06', 'CUILCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '07', 'JACALTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '08', 'LA DEMOCRACIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '09', 'LA LIBERTAD'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '10', 'MALACATANCITO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '11', 'NENTON'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '12', 'PETATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '13', 'SAN ANTONIO HUISTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '14', 'SAN GASPAR IXCHIL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '15', 'SAN ILDEFONSO IXTAHUACAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '16', 'SAN JUAN ATITAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '17', 'SAN JUAN IXCOY'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '18', 'SAN MATEO IXTATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '19', 'SAN MIGUEL ACATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '20', 'SAN PEDRO NECTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '21', 'SAN PEDRO SOLOMA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '22', 'SAN RAFAEL LA INDEPENDENCIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '23', 'SAN RAFAEL PETZAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '24', 'SAN SEBASTIAN COATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '25', 'SAN SEBASTIAN HUEHUETENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '26', 'SANTA ANA HUISTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '27', 'SANTA BARBARA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '28', 'SANTA CRUZ BARILLAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '29', 'SANTA EULALIA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '30', 'SANTIAGO CHIMALTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '31', 'TECTITAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '32', 'TODOS SANTOS CUCHUMATAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '13'), '33', 'UNION CANTINIL'),

-- EL QUICHE
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '01', 'SANTA CRUZ DEL QUICHE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '02', 'CANILLA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '03', 'CHAJUL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '04', 'CHICAMAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '05', 'CHICHE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '06', 'CHICHICASTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '07', 'CHINIQUE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '08', 'CUNEN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '09', 'IXCAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '10', 'JOYABAJ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '11', 'NEBAJ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '12', 'PACHALUM'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '13', 'PATZITE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '14', 'SACAPULAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '15', 'SAN ANDRES SAJCABAJA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '16', 'SAN ANTONIO ILOTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '17', 'SAN BARTOLOME JOCOTENANGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '18', 'SAN JUAN COTZAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '19', 'SAN PEDRO JOCOPILAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '20', 'USPANTAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '14'), '21', 'ZACUALPA'),

-- BAJA VERAPAZ
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '01', 'SALAMA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '02', 'CUBULCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '03', 'GRANADOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '04', 'PURULHA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '05', 'RABINAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '06', 'SAN JERONIMO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '07', 'SAN MIGUEL CHICAJ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '15'), '08', 'SANTA CRUZ EL CHOL'),

-- ALTA VERAPAZ
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '01', 'COBAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '02', 'SANTA CRUZ VERAPAZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '03', 'SAN CRISTOBAL VERAPAZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '04', 'TACTIC'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '05', 'TAMAHU'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '06', 'TUCURU'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '07', 'PANZOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '08', 'SENAHU'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '09', 'SAN PEDRO CARCHA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '10', 'SAN JUAN CHAMELCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '11', 'LANQUIN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '12', 'CAHABON'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '13', 'CHISEC'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '14', 'CHAHAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '15', 'FRAY BARTOLOME DE LAS CASAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '16', 'SANTA CATALINA LA TINTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '16'), '17', 'RAXRUHA'),

-- PETEN
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '01', 'FLORES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '02', 'SAN JOSE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '03', 'SAN BENITO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '04', 'SAN ANDRES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '05', 'SAN FRANCISCO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '06', 'SANTA ANA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '07', 'DOLORES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '08', 'SAN LUIS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '09', 'SAYAXCHE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '10', 'MELCHOR DE MENCOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '11', 'POPTUN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '12', 'LAS CRUCES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '13', 'EL CHAL'),
((SELECT departamento_id FROM departamentos WHERE codigo = '17'), '14', 'LA LIBERTAD'),

-- IZABAL
((SELECT departamento_id FROM departamentos WHERE codigo = '18'), '01', 'PUERTO BARRIOS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '18'), '02', 'LIVINGSTON'),
((SELECT departamento_id FROM departamentos WHERE codigo = '18'), '03', 'EL ESTOR'),
((SELECT departamento_id FROM departamentos WHERE codigo = '18'), '04', 'MORALES'),
((SELECT departamento_id FROM departamentos WHERE codigo = '18'), '05', 'LOS AMATES'),

-- ZACAPA
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '01', 'ZACAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '02', 'ESTANZUELA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '03', 'RIO HONDO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '04', 'GUALAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '05', 'TECULUTAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '06', 'USUMATLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '07', 'CABANAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '08', 'SAN DIEGO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '09', 'LA UNION'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '10', 'HUITE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '19'), '11', 'SAN JORGE'),

-- CHIQUIMULA
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '01', 'CHIQUIMULA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '02', 'CAMOTAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '03', 'CONCEPCION LAS MINAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '04', 'ESQUIPULAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '05', 'IPALA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '06', 'JOCOTAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '07', 'OLOPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '08', 'QUETZALTEPEQUE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '09', 'SAN JACINTO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '10', 'SAN JOSE LA ARADA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '20'), '11', 'SAN JUAN ERMITA'),

-- JALAPA
((SELECT departamento_id FROM departamentos WHERE codigo = '21'), '01', 'JALAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '21'), '02', 'SAN PEDRO PINULA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '21'), '03', 'SAN LUIS JILOTEPEQUE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '21'), '04', 'SAN MANUEL CHAPARRON'),
((SELECT departamento_id FROM departamentos WHERE codigo = '21'), '05', 'SAN CARLOS ALZATATE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '21'), '06', 'MONJAS'),
((SELECT departamento_id FROM departamentos WHERE codigo = '21'), '07', 'MATAQUESCUINTLA'),

-- JUTIAPA
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '01', 'JUTIAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '02', 'ASUNCION MITA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '03', 'ATESCATEMPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '04', 'COMAPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '05', 'CONGUACO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '06', 'EL ADELANTO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '07', 'EL PROGRESO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '08', 'JALPATAGUA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '09', 'JEREZ'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '10', 'MOYUTA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '11', 'PASACO'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '12', 'QUESADA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '13', 'SAN JOSE ACATEMPA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '14', 'SANTA CATARINA MITA'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '15', 'YUPILTEPEQUE'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '16', 'ZAPOTITLAN'),
((SELECT departamento_id FROM departamentos WHERE codigo = '22'), '17', 'AGUA BLANCA');
